// Ejecutar únicamente contra una base temporal nueva. Usa el servicio local indicado en API_PORT.
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
const smokePassword=process.env.IGLESIA_SMOKE_PASSWORD??`${randomBytes(32).toString('base64url')}Aa1!`;
const changedPassword=`${randomBytes(32).toString('base64url')}Bb2!`;
const host=`http://127.0.0.1:${process.env.API_PORT??4317}`;let token='';
async function req(path,method='GET',body){const r=await fetch(host+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
assert.equal((await req('/health')).status,200);
const setup=await req('/setup/status');assert.equal(setup.data.initialized,false,'Use una base temporal sin usuarios');
assert.equal((await req('/setup','POST',{username:'prueba_admin',password:smokePassword,name:'Iglesia Roca de Salvación'})).status,201);
assert.equal((await req('/setup','POST',{username:'otro_admin',password:smokePassword,name:'Otra'})).status,409);
const login=await req('/auth/login','POST',{username:'prueba_admin',password:smokePassword});assert.equal(login.status,200);token=login.data.token;
const roles=(await req('/api/roles')).data;const consulta=roles.find(r=>r.name==='Consulta');
const user=await req('/api/users','POST',{username:'prueba_lector',password:smokePassword,role_id:Number(consulta.id)});assert.equal(user.status,201);
const m=await req('/api/members','POST',{first_name:'Prueba',last_name:'Temporal',status:'activo',new_family:true,cedula:'000-0000000-0',sex:'Femenino',birth_date:'1990-01-01',address:'Dirección de prueba',children_count:2});assert.equal(m.status,201);
const id=m.data.id;assert.match(m.data.family_code,/^F-\d{4,}$/);assert.equal((await req('/api/families')).data.some(f=>f.code===m.data.family_code),true);assert.equal((await req(`/api/members/${id}`,'PUT',{first_name:'Prueba',last_name:'Actualizada',status:'activo',family_code:m.data.family_code,cedula:'000-0000000-0',sex:'Femenino',birth_date:'1990-01-01',address:'Dirección de prueba',children_count:2})).data.status,'activo');
assert.equal((await req('/api/members')).data.find(x=>x.id===id).last_name,'Actualizada');assert.equal((await req('/api/members')).data.find(x=>x.id===id).children_count,2);
assert.equal((await req('/api/audit')).data.some(a=>a.action==='create'&&a.entity==='members'),true);
const week='2026-09-28';const base=`/api/program/weeks/${week}`;
assert.equal((await req(base+'/init','POST')).status,201);
let current=(await req(base)).data;assert.equal(current.cults.find(c=>c.day_offset===2).cult_name,'Culto de Caballeros');
assert.equal((await req(base+'/cults/2','PUT',{day_offset:2,cult_name:'Culto de Damas',starts_at:'19:00',topic_word:'Perdón',memory_instruction:'Busque un versículo que contenga Perdón',manual_override:true})).status,200);
let item=(await req(base+'/cults/2/items','POST',{position:1,activity:'Oración',member_id:Number(m.data.id),starts_at:'19:10',minutes:10,topic:'Por las familias',scripture:'Salmo 23',status:'Pendiente'}));assert.equal(item.status,201);assert.equal((await req(base+'/cults/2/items','POST',{position:2,activity:'Lectura',responsible_name:'Nombre manual'})).status,400);assert.equal((await req('/api/program/assignable-members')).data.some(x=>String(x.id)===String(id)),true);
const itemId=item.data.cults.find(c=>c.day_offset===2).items[0].id;
assert.equal((await req(base+'/invitations','POST',{event_date:'2026-09-30',entity:'Iglesia vecina',activity:'Culto especial',modality:'Presencial'})).status,201);
assert.equal((await req(base+'/publish','POST')).data.revision,1);
assert.equal((await req(base+`/items/${itemId}`,'PUT',{position:1,activity:'Dirección',member_id:Number(m.data.id),status:'Confirmado'})).status,200);
assert.equal((await req(base+'/publish','POST')).data.revision,2);
const v1=(await req(base+'/publications/1')).data.snapshot;
const v2=(await req(base+'/publications/2')).data.snapshot;
assert.equal(v1.cults.find(c=>c.day_offset===2).items[0].activity,'Oración');
assert.equal(v2.cults.find(c=>c.day_offset===2).items[0].activity,'Dirección');
assert.equal((await req('/api/program/weeks/2026-10-05/init','POST')).data.cults.find(c=>c.day_offset===2).cult_name,'Culto de Caballeros');
const budgetRole=roles.find(r=>r.name==='Finanzas Aprobación');const payRole=roles.find(r=>r.name==='Finanzas Pagos');
const approver=await req('/api/users','POST',{username:'prueba_aprobador',password:smokePassword,role_id:Number(budgetRole.id)});assert.equal(approver.status,201);
const payer=await req('/api/users','POST',{username:'prueba_pagador',password:smokePassword,role_id:Number(payRole.id)});assert.equal(payer.status,201);
const account=Number((await req('/api/finance/accounts')).data[0].id),society=Number((await req('/api/program/societies')).data[0].id);
const expense=await req('/api/finance/entries','POST',{kind:'gasto',society_id:society,occurred_on:'2026-09-28',category:'Mantenimiento',description:'Prueba',amount_cents:2500});assert.equal(expense.status,201);
assert.equal((await req(`/api/finance/entries/${expense.data.id}/decision`,'POST',{decision:'aprobado'})).status,409);
const financeAdminToken=token;token=(await req('/auth/login','POST',{username:'prueba_aprobador',password:smokePassword})).data.token;
assert.equal((await req(`/api/finance/entries/${expense.data.id}/decision`,'POST',{decision:'aprobado'})).status,200);
assert.equal((await req(`/api/finance/entries/${expense.data.id}/pay`,'POST',{account_id:account})).status,403);
token=(await req('/auth/login','POST',{username:'prueba_pagador',password:smokePassword})).data.token;
assert.equal((await req(`/api/finance/entries/${expense.data.id}/pay`,'POST',{account_id:account})).status,200);
token=financeAdminToken;
assert.equal((await req('/api/finance/entries','POST',{kind:'ingreso',society_id:society,account_id:account,occurred_on:'2026-09-28',category:'Ofrenda',amount_cents:10000})).status,201);
const summary=(await req('/api/finance/summary')).data;assert.equal(Number(summary.incomes_cents),10000);assert.equal(Number(summary.expenses_cents),2500);assert.equal(Number(summary.accounts[0].balance_cents),7500);
assert.equal((await req('/api/finance/budgets','PUT',{society_id:society,year:2026,month:9,amount_cents:20000})).status,200);
assert.equal((await req(`/api/finance/outlines/${itemId}`,'PUT',{title:'Esperanza',base_text:'Salmo 23'})).status,200);
assert.equal((await req(`/api/finance/outlines/${itemId}`)).data.title,'Esperanza');
if(!process.env.SKIP_BACKUP){const backup=await req('/api/backups','POST');assert.equal(backup.status,201);assert.match(backup.data.sha256,/^[a-f0-9]{64}$/);assert.equal((await req(`/api/backups/${backup.data.name}/restore-request`,'POST')).status,200);}
assert.equal((await req(`/api/members/${id}`,'DELETE')).status,200);assert.equal((await req(base+'/publications/1')).data.snapshot.cults.find(c=>c.day_offset===2).items[0].activity,'Oración');
assert.equal((await req(`/api/users/${user.data.id}`,'PUT',{role_id:Number(consulta.id),active:true,password:changedPassword})).status,200);
const adminToken=token;token='';assert.equal((await req('/auth/login','POST',{username:'prueba_lector',password:changedPassword})).status,200);token=(await req('/auth/login','POST',{username:'prueba_lector',password:changedPassword})).data.token;assert.equal((await req('/api/members')).status,200);assert.equal((await req('/api/users')).status,403);assert.equal((await req(base+'/publish','POST')).status,403);assert.equal((await req('/api/members','POST',{first_name:'X',last_name:'Y'})).status,403);
token=adminToken;assert.equal((await req('/api/auth/logout','POST')).status,200);assert.equal((await req('/api/me')).status,401);
console.log('Humo PostgreSQL/API: configuración, miembros, programación, finanzas, bosquejos, respaldo y permisos OK');
