import {Router,type Request,type Response,type NextFunction} from 'express';import {z} from 'zod';import {db,audit} from './db.js';import {weekSchema,cultSchema,itemSchema,invitationSchema,defaultCult,validateCult} from './program.js';
const router=Router();const wrap=(f:(q:Request,r:Response)=>Promise<unknown>)=>(q:Request,r:Response,n:NextFunction)=>{Promise.resolve(f(q,r)).catch(n)};
const permit=(code:string)=>(q:Request,r:Response,n:NextFunction)=>q.auth?.perms.has(code)?n():r.status(403).json({error:'Permiso insuficiente'});
const week=(q:Request)=>weekSchema.parse(String(q.params.week));
async function detail(start:string){const p=await db.query('SELECT id,week_start,created_at,updated_at FROM weekly_programs WHERE week_start=$1',[start]);if(!p.rowCount)return null;const id=p.rows[0].id;const [c,i,v,versions]=await Promise.all([
 db.query('SELECT * FROM weekly_cults WHERE program_id=$1 ORDER BY day_offset',[id]),
 db.query("SELECT wi.*,COALESCE(NULLIF(wi.responsible_name,''),trim(concat_ws(' ',m.first_name,m.last_name))) display_name,wc.day_offset FROM weekly_items wi JOIN weekly_cults wc ON wc.id=wi.cult_id LEFT JOIN members m ON m.id=wi.member_id WHERE wc.program_id=$1 ORDER BY wc.day_offset,wi.position",[id]),
 db.query('SELECT * FROM weekly_invitations WHERE program_id=$1 ORDER BY event_date,event_time',[id]),
 db.query('SELECT id,revision,created_at FROM weekly_publications WHERE program_id=$1 ORDER BY revision DESC',[id])]);return {...p.rows[0],cults:c.rows.map(row=>({...row,items:i.rows.filter(item=>String(item.cult_id)===String(row.id))})),invitations:v.rows,publications:versions.rows}}
router.get('/assignable-members',permit('program.read'),wrap(async(_q,r)=>r.json((await db.query("SELECT id,first_name,last_name,phone FROM members WHERE status='activo' ORDER BY first_name,last_name LIMIT 1000")).rows)));
router.get('/societies',permit('program.read'),wrap(async(_q,r)=>r.json((await db.query('SELECT id,name,kind,active FROM societies ORDER BY id')).rows)));
router.get('/weeks/:week',permit('program.read'),wrap(async(q,r)=>r.json(await detail(week(q)))));
router.post('/weeks/:week/init',permit('program.write'),wrap(async(q,r)=>{const start=week(q);const c=await db.connect();try{await c.query('BEGIN');const p=await c.query('INSERT INTO weekly_programs(week_start,created_by) VALUES($1,$2) ON CONFLICT(week_start) DO UPDATE SET week_start=EXCLUDED.week_start RETURNING id',[start,q.auth!.id]);const previous=await c.query("SELECT cult_name FROM weekly_cults wc JOIN weekly_programs wp ON wp.id=wc.program_id WHERE wp.week_start<$1 AND wc.day_offset=2 AND cult_name IN ('Culto de Damas','Culto de Caballeros') ORDER BY wp.week_start DESC LIMIT 1",[start]);const last=previous.rows[0]?.cult_name==='Culto de Caballeros'?'Caballeros':'Damas';for(const day of [1,2,3,6] as const){const x=defaultCult(start,day,last);await c.query('INSERT INTO weekly_cults(program_id,day_offset,cult_name,starts_at) VALUES($1,$2,$3,$4) ON CONFLICT(program_id,day_offset) DO NOTHING',[p.rows[0].id,day,x.cult_name,x.starts_at])}await c.query('COMMIT');await audit(q.auth!.id,'create_or_open','weekly_programs',String(p.rows[0].id));r.status(201).json(await detail(start))}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.put('/weeks/:week/cults/:day',permit('program.write'),wrap(async(q,r)=>{const start=week(q),day=Number(q.params.day);const b=cultSchema.parse(q.body);if(b.day_offset!==day){r.status(400).json({error:'El día no coincide'});return}const p=await detail(start);if(!p){r.status(404).json({error:'Semana no encontrada'});return}validateCult(p.cults.filter((x:any)=>x.day_offset!==day),b);const current=p.cults.find((x:any)=>x.day_offset===day);if(!current){r.status(404).json({error:'Culto no encontrado'});return}if(current.cult_name!==b.cult_name&&!b.manual_override){r.status(400).json({error:'Marque selección manual para cambiar el culto propuesto'});return}await db.query('UPDATE weekly_cults SET cult_name=$1,starts_at=$2,topic_word=$3,memory_instruction=$4,manual_override=$5 WHERE id=$6',[b.cult_name,b.starts_at,b.topic_word,b.memory_instruction,b.manual_override,current.id]);await db.query('UPDATE weekly_programs SET updated_at=now() WHERE id=$1',[p.id]);await audit(q.auth!.id,'update','weekly_cults',String(current.id));r.json(await detail(start))}));
router.post('/weeks/:week/cults/:day/items',permit('program.write'),wrap(async(q,r)=>{const start=week(q),day=Number(q.params.day),b=itemSchema.parse(q.body);const active=await db.query("SELECT 1 FROM members WHERE id=$1 AND status='activo'",[b.member_id]);if(!active.rowCount){r.status(400).json({error:'Seleccione un miembro activo'});return}const p=await detail(start),cult=p?.cults.find((x:any)=>x.day_offset===day);if(!cult){r.status(404).json({error:'Culto no encontrado'});return}const result=await db.query('INSERT INTO weekly_items(cult_id,position,activity,member_id,responsible_name,starts_at,minutes,topic,scripture,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id',[cult.id,b.position,b.activity,b.member_id??null,b.responsible_name,b.starts_at??null,b.minutes??null,b.topic,b.scripture,b.status,b.notes]);await audit(q.auth!.id,'create','weekly_items',String(result.rows[0].id));r.status(201).json(await detail(start))}));
router.put('/weeks/:week/items/:id',permit('program.write'),wrap(async(q,r)=>{const start=week(q),b=itemSchema.parse(q.body);const active=await db.query("SELECT 1 FROM members WHERE id=$1 AND status='activo'",[b.member_id]);if(!active.rowCount){r.status(400).json({error:'Seleccione un miembro activo'});return}const p=await detail(start);if(!p){r.status(404).json({error:'Semana no encontrada'});return}const x=await db.query('UPDATE weekly_items SET position=$1,activity=$2,member_id=$3,responsible_name=$4,starts_at=$5,minutes=$6,topic=$7,scripture=$8,status=$9,notes=$10 WHERE id=$11 AND cult_id IN (SELECT id FROM weekly_cults WHERE program_id=$12) RETURNING id',[b.position,b.activity,b.member_id??null,b.responsible_name,b.starts_at??null,b.minutes??null,b.topic,b.scripture,b.status,b.notes,q.params.id,p.id]);if(!x.rowCount){r.status(404).json({error:'Oportunidad no encontrada'});return}await audit(q.auth!.id,'update','weekly_items',String(q.params.id));r.json(await detail(start))}));
router.delete('/weeks/:week/items/:id',permit('program.write'),wrap(async(q,r)=>{const start=week(q),p=await detail(start);if(!p){r.status(404).json({error:'Semana no encontrada'});return}const x=await db.query('DELETE FROM weekly_items WHERE id=$1 AND cult_id IN (SELECT id FROM weekly_cults WHERE program_id=$2) RETURNING id',[q.params.id,p.id]);if(!x.rowCount){r.status(404).json({error:'Oportunidad no encontrada'});return}await audit(q.auth!.id,'delete','weekly_items',String(q.params.id));r.json(await detail(start))}));
router.post('/weeks/:week/invitations',permit('program.write'),wrap(async(q,r)=>{const start=week(q),b=invitationSchema.parse(q.body),p=await detail(start);const end=new Date(start+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+6);if(b.event_date<start||b.event_date>end.toISOString().slice(0,10)){r.status(400).json({error:'La invitación debe corresponder a esta semana'});return}if(!p){r.status(404).json({error:'Semana no encontrada'});return}const x=await db.query('INSERT INTO weekly_invitations(program_id,event_date,event_time,entity,activity,place,contact,phone,modality,responsible,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id',[p.id,b.event_date,b.event_time??null,b.entity,b.activity,b.place,b.contact,b.phone,b.modality,b.responsible,b.status,b.notes]);await audit(q.auth!.id,'create','weekly_invitations',String(x.rows[0].id));r.status(201).json(await detail(start))}));
router.delete('/weeks/:week/invitations/:id',permit('program.write'),wrap(async(q,r)=>{const p=await detail(week(q));if(!p){r.status(404).json({error:'Semana no encontrada'});return}const x=await db.query('DELETE FROM weekly_invitations WHERE id=$1 AND program_id=$2 RETURNING id',[q.params.id,p.id]);if(!x.rowCount){r.status(404).json({error:'Invitación no encontrada'});return}await audit(q.auth!.id,'delete','weekly_invitations',String(q.params.id));r.json(await detail(week(q)))}));
router.post('/weeks/:week/publish',permit('program.publish'),wrap(async(q,r)=>{const start=week(q);const c=await db.connect();try{await c.query('BEGIN');const locked=await c.query('SELECT id FROM weekly_programs WHERE week_start=$1 FOR UPDATE',[start]);if(!locked.rowCount){await c.query('ROLLBACK');r.status(404).json({error:'Semana no encontrada'});return}const p=await detail(start);if(!p!.cults.some((x:any)=>x.items.length)){await c.query('ROLLBACK');r.status(400).json({error:'Agregue al menos una oportunidad antes de publicar'});return}const v=await c.query('SELECT COALESCE(MAX(revision),0)+1 AS n FROM weekly_publications WHERE program_id=$1',[p!.id]);const n=Number(v.rows[0].n);const snapshot={week_start:start,cults:p!.cults,invitations:p!.invitations};await c.query('INSERT INTO weekly_publications(program_id,revision,snapshot,created_by) VALUES($1,$2,$3,$4)',[p!.id,n,JSON.stringify(snapshot),q.auth!.id]);await c.query('INSERT INTO audit(actor_id,action,entity,entity_id,detail) VALUES($1,$2,$3,$4,$5)',[q.auth!.id,'publish','weekly_publications',String(p!.id),JSON.stringify({revision:n})]);await c.query('COMMIT');r.status(201).json({revision:n,snapshot})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.get('/weeks/:week/publications/:revision',permit('program.read'),wrap(async(q,r)=>{const x=await db.query('SELECT wp.snapshot,wp.revision,wp.created_at FROM weekly_publications wp JOIN weekly_programs p ON p.id=wp.program_id WHERE p.week_start=$1 AND wp.revision=$2',[week(q),q.params.revision]);if(!x.rowCount){r.status(404).json({error:'Versión no encontrada'});return}r.json(x.rows[0])}));
export default router;
